[package]
name = "habi"
version = "0.1.0"
authors = ["mato"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.0.0"
rand = "0.7.3"
rodio = "0.12.0"
