[package]
name = "habi"
version = "0.1.0"
authors = ["mato"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
log = "0.4.11"
notify-rust = "4.2.2"
rand = "0.7.3"
rodio = "0.13.0"
